# Generated by Django 4.2.4 on 2023-08-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Category title')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Category address')),
                ('status', models.BooleanField(default=True, verbose_name='Is it displayed?')),
                ('position', models.IntegerField(verbose_name='position')),
            ],
            options={
                'verbose_name': 'Grouping',
                'verbose_name_plural': 'categories',
                'ordering': ['position'],
            },
        ),
    ]
