# Generated by Django 2.2.11 on 2020-06-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200418_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='Special article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', 'Draft\u200c'), ('p', 'published'), ('i', 'Pending'), ('b', 'returned')], max_length=1, verbose_name='وضعیت'),
        ),
    ]